# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download_strategy"
class Analytics < Formula
  desc ""
  homepage "https://github.com/weave-lab/analytics-etl"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/weave-lab/analytics-etl/releases/download/v0.1.1/analytics-etl_0.1.1_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "7034a34ab7f763ecc7606e9b9b993ef3f9848bdb3b7578f274dd2f8e6f16086c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/weave-lab/analytics-etl/releases/download/v0.1.1/analytics-etl_0.1.1_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d14ad190c5ac9617bfa2e7f877832705e9e33e11e25b9c90a5bedd3696ad6cac"
    end
  end

  def install
    bin.install "analytics"
  end
end
