# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download_strategy"
class Analytics < Formula
  desc ""
  homepage "https://github.com/weave-lab/data-wvtutils"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/weave-lab/data-wvtutils/releases/download/v0.0.4/data-wvtutils_0.0.4_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "92035a7cef1bea1dc1d6e4f2158fd7db1761656cb2f75feac5e08e3e9f7b2344"
  elsif OS.linux?
  end

  def install
    bin.install "wvtutils"
  end
end
