# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download_strategy"
class Bart < Formula
  desc ""
  homepage "https://github.com/weave-lab/bart"
  version "1.13.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/weave-lab/bart/releases/download/v1.13.5/bart_1.13.5_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "15ba2c432e457d3e5792cbd58737ffbb20f0d7970cbccf5622e50acc46f88e1a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/weave-lab/bart/releases/download/v1.13.5/bart_1.13.5_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fbdab9e11687b0f54a91349909620dc53fd9f411c171d03179c3e4f85a7f057e"
    end
  end

  def install
    bin.install "bart"
  end
end
