# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download_strategy"
class Bart < Formula
  desc ""
  homepage "https://github.com/weave-lab/bart"
  version "1.0.341"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/weave-lab/bart/releases/download/v1.0.341/bart_1.0.341_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "ba47eae050e1c004b9dbd78db0311eca7e92e3fd52c7ebf6daebce14bda83625"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/weave-lab/bart/releases/download/v1.0.341/bart_1.0.341_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fcd2637981faf84a3ce34114f23b6aab493c28646e274fe8923c04a92a806f4f"
    end
  end

  def install
    bin.install "bart"
  end
end
