# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download_strategy"
class Bart < Formula
  desc ""
  homepage "https://github.com/weave-lab/bart"
  url "https://github.com/weave-lab/bart/releases/download/v1.0.80/bart_1.0.80_Darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
  version "1.0.80"
  sha256 "505234db39082e79c51d77d4c320d4f746f24b83952318b995ade808ff1eaafd"

  def install
    bin.install "bart"
  end
end
