# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../download_strategy"
class Devx513 < Formula
  desc ""
  homepage "https://github.com/weave-lab/devx-513"
  version "0.0.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/weave-lab/devx-513/releases/download/v0.0.8/devx-513_0.0.8_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "eddeee257bf998cf30e607e1a2becbc60da5ce2b35847bc83bf4c79369e37b46"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/weave-lab/devx-513/releases/download/v0.0.8/devx-513_0.0.8_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "460b3ca1aaa4dabc970ab6de734a657ccf46c6e18af6247f77f38778cc2d2917"
    end
  end

  def install
    bin.install "devx-513"
  end
end
